version: '3.8'

services:

  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped 
    command: gunicorn -w 1 -b 0.0.0.0:8080 wsgi:app

  nginx:
    container_name: nginx
    image: nginx:latest
    depends_on:
      - api
    ports:
      - "5000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
